# ============================================================================
# 🔒 .streamlit/secrets.toml - SECRETS LOCAIS (NÃO VERSIONAR!)
# ============================================================================
# Para desenvolvimento local - NÃO VERSIONAR ESTE ARQUIVO!

[auth]
cookie_key = "change_this_secret_key_in_production"
admin_password = "admin123"
user_password = "user123"

[database]
# Configurações de banco se necessário no futuro
host = "localhost"
username = "user"
password = "password"
